import { useState } from 'react'

const faqItems = [
  {
    q: 'Where can I find your books?',
    a: 'Amazon, Barnes & Noble, and potentially your local library or bookstore soon! (coming soon)',
  },
  {
    q: 'Do you have any themed merchandise?',
    a: "As of right now, there isn't much to offer because projects are still growing. Merchandise is definitely in the bucket list though — you'll probably see it down the road!",
  },
  {
    q: 'Do you do book signings?',
    a: 'Potentially at ComicCON or AnimeCON, or at local bookstores & libraries. Dates are undetermined but this is definitely in the bucket list for when the worlds grow larger!',
  },
  {
    q: 'What kind of mediums do you do?',
    a: "A lot of different stuff! Painting and 3D Printing, along with laser engraving. Though these haven't been tinkered with in a long time.",
  },
  {
    q: 'Favorite Creation?',
    a: 'Cordis Ignis et Animi, one of the music compositions, is by far one of the favorites. But there are so many to choose from!',
  },
  {
    q: 'Favorite medium to create with?',
    a: "Definitely music. It's just so fun!",
  },
  {
    q: 'Least favorite creation?',
    a: 'Equally all creations are loved, but the Everfrøst Series music album is a tough one — stuck on finishing the last two tracks for a long time.',
  },
  {
    q: "What's the next big thing?",
    a: 'Honest answer? No idea. But one bucket list item is jumping into animation!',
  },
  {
    q: 'Inspirations?',
    a: 'Many different pop culture media — anime, TV Shows, and movies. The biggest and core inspiration is Mob Psycho 100.',
  },
  {
    q: 'Favorite books growing up?',
    a: 'Magic School Bus, Magic Tree House, Alex Rider, Jack Reacher, and many more.',
  },
  {
    q: 'Other pastimes?',
    a: "Sleep. It's important. Also cuddling with the dog, and chilling — vibes very easily.",
  },
]

const morals = [
  {
    color: 'gold',
    label: 'Credibility and Fair Use',
    desc: 'When someone wants to use work in quotes or reviews, crediting back to the author or original source is crucial. Without proper consent, it is considered theft, piracy, and stealing — something that is not tolerated.',
  },
  {
    color: 'gold',
    label: 'Being Honest',
    desc: 'Entitlement with a high ego is hated. People cannot learn without making mistakes. We as humans are not perfect. We can use our mistakes to learn from them and do better.',
  },
  {
    color: 'gold',
    label: 'Constructive Criticism',
    desc: 'A firm believer in constructive and positive criticism. It allows improvement of self and projects. Hate or harsh criticism is not tolerated, as it undermines talents.',
  },
]

const donts = [
  "Content Piracy — Stolen or pirated content will be traced, documented, and taken down. DO NOT copy everything word for word!",
  'NSFW/18+ Works — Adult content inspired by this content is not allowed. No derogatory content, fetishization, or sexualization.',
  'Repurposing Art — Designs, images, tracing, printing and selling on illegal websites is not allowed.',
  'Generative AI Art — This will NOT be tolerated. It inhibits freedom of self expression. All content generated by AI will be asked to be taken down.',
  'Impersonation — Do not replicate work, content, art, or music. Reputation must be respected. What is created is sacred.',
]

const dos = [
  'Cosplay, fandoms, and anything related to expressing creativeness by showing support of favorite series.',
  'Fan Creations (sticker production, plushies, etc.) — creative community engagement is encouraged!',
  'An Animated TV Adaptation — definitely on the bucket list!',
]

function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  return (
    <div className="space-y-2">
      {faqItems.map((item, i) => (
        <div key={i} className="bg-surface border border-border rounded-lg overflow-hidden">
          <button
            onClick={() => setOpenIndex(openIndex === i ? null : i)}
            className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-surface-raised transition-colors"
          >
            <span className="text-sm font-medium text-text">{item.q}</span>
            <svg
              className={`w-4 h-4 text-text-faint flex-shrink-0 ml-3 transition-transform duration-200 ${
                openIndex === i ? 'rotate-180' : ''
              }`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          {openIndex === i && (
            <div className="px-5 pb-4">
              <p className="text-sm text-text-muted leading-relaxed">{item.a}</p>
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

export default function Policies() {
  return (
    <div className="pt-16">
      <div className="max-w-4xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="page-hero">
          <p className="text-rose text-xs font-medium tracking-widest uppercase mb-3">
            Legal & Beliefs
          </p>
          <h1 className="font-serif text-4xl sm:text-5xl font-bold text-text mb-4">
            Policies & Beliefs
          </h1>
          <p className="text-text-muted leading-relaxed">
            A little FAQ and policy section based on my beliefs as an artist and creator! As an
            author and artist of all different mediums, there are certain things that are important
            and crucial when it comes to creating works of fiction and putting it out in the world.
          </p>
        </div>

        {/* Morals */}
        <section className="mb-12">
          <h2 className="font-serif text-2xl font-semibold text-text mb-6">
            Morals I Believe in as an Artist
          </h2>
          <div className="space-y-4">
            {morals.map((moral, i) => (
              <div key={i} className="flex items-start gap-4 p-5 bg-surface rounded-xl border border-border">
                <span className="flex-shrink-0 w-7 h-7 rounded-full bg-gold-bg border border-gold/30 flex items-center justify-center text-xs font-bold text-gold">
                  {i + 1}
                </span>
                <div>
                  <h3 className="font-semibold text-gold-light text-sm mb-1">{moral.label}</h3>
                  <p className="text-sm text-text-muted leading-relaxed">{moral.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <div className="section-divider" />

        {/* Don'ts */}
        <section className="mb-12">
          <h2 className="font-serif text-2xl font-semibold text-text mb-2">What I Won't Allow</h2>
          <p className="text-text-muted text-sm mb-6">
            All creations are original work and automatically claimed under the Federal Copyright Act
            of 1976.
          </p>
          <div className="space-y-3">
            {donts.map((item, i) => (
              <div
                key={i}
                className="flex items-start gap-3 p-4 bg-surface rounded-lg border border-border border-l-2 border-l-error"
              >
                <span className="text-error flex-shrink-0 mt-0.5">✗</span>
                <p className="text-sm text-text-muted leading-relaxed">{item}</p>
              </div>
            ))}
          </div>

          <div className="mt-6 p-4 bg-surface rounded-lg border border-border">
            <h3 className="font-semibold text-text text-sm mb-2">Live Action Adaptations</h3>
            <p className="text-xs text-text-muted leading-relaxed">
              Not a fan of live action adaptations, because content like this is not 100% accurate to
              the original source, thus doing the content no justice. It just won't work!
            </p>
          </div>
        </section>

        {/* Do's */}
        <section className="mb-12">
          <h2 className="font-serif text-2xl font-semibold text-text mb-6">What I'll Allow</h2>
          <div className="space-y-3">
            {dos.map((item, i) => (
              <div
                key={i}
                className="flex items-start gap-3 p-4 bg-surface rounded-lg border border-border border-l-2 border-l-success"
              >
                <span className="text-success flex-shrink-0 mt-0.5">✓</span>
                <p className="text-sm text-text-muted leading-relaxed">{item}</p>
              </div>
            ))}
          </div>
        </section>

        <div className="section-divider" />

        {/* FAQ */}
        <section>
          <h2 className="font-serif text-2xl font-semibold text-text mb-2">
            Frequently Asked Questions
          </h2>
          <p className="text-text-muted text-sm mb-6">
            You might have some questions! Hopefully this answers most of your curiosity.
          </p>
          <FAQ />
        </section>
      </div>
    </div>
  )
}
